# Generated by Django 2.2.1 on 2020-09-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
        ('blog', '0004_auto_20200831_2147'),
    ]

    operations = [
    ]
